#line 2 "lex_sql.cpp"
/*
这里的代码会被复制到lex_sql.cpp的最开始位置
定义yy_size_t的原因是因为flex生成的代码，会使用yy_size_t与其他类型的数字
做比较，导致编译报警
*/
#define YY_TYPEDEF_YY_SIZE_T
typedef int yy_size_t;

/* 参考生成的lex_sql.cpp代码，这个宏定义会放在每次运行yylex()最开始的地方 */
#define YY_USER_INIT                                         \
  yycolumn = 0;

/* 参考生成的lex_sql.cpp代码，这个宏定义会放在解析一个token之后，也可以在网上找到大量的参考资料 */
/* 我们在这里设置当前解析的token的位置信息，这样在yacc中就可以使用这些信息了 */
#define YY_USER_ACTION                                       \
do {                                                         \
  yylloc->first_line   = yylloc->last_line = yylineno;       \
  yylloc->first_column = yycolumn;                           \
  yylloc->last_column  = yylloc->first_column + yyleng - 1;  \
  yycolumn += yyleng;                                        \
}                                                            \
while (0);

#line 26 "lex_sql.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

#ifdef yyget_lloc
#define yyget_lloc_ALREADY_DEFINED
#else
#define yyget_lloc yyget_lloc
#endif

#ifdef yyset_lloc
#define yyset_lloc_ALREADY_DEFINED
#else
#define yyset_lloc yyset_lloc
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[275] =
    {   0,
        0,    0,    0,    0,   79,   77,    1,    2,   77,   77,
       77,   61,   62,   73,   71,   63,   72,   11,   74,    3,
        5,   68,   64,   70,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   78,   67,    0,   75,    0,
        0,   76,    0,    3,    0,   65,   66,   69,   59,   59,
       59,   59,   59,   46,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   56,   59,   59,
       59,   59,   59,   59,   59,   20,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,    0,    0,    4,   27,

        8,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   37,   59,   59,   59,   59,    6,    7,   59,
       59,   59,   59,   33,   59,   59,    9,   59,   59,   59,
       59,   59,    0,    0,   59,   24,   38,   59,   59,   59,
       42,   40,   59,   14,   16,   59,   12,   59,   59,   59,
       25,   59,   13,   59,   59,   59,   59,   29,   50,   59,
       54,   41,    0,   59,   59,   59,   21,   59,   22,   59,
       59,   59,   59,    0,    0,   34,   59,   10,   59,   59,
       59,   59,   59,   39,   59,   45,   19,   59,   59,   59,

       59,    0,    0,    0,   59,   48,   59,   59,   17,   59,
       59,   26,    0,    0,   35,   15,   59,   31,   57,   59,
       52,   43,    0,   28,   47,    0,   55,    0,   59,   23,
       59,   18,   32,   30,    0,    0,    0,    0,    0,    0,
       59,   44,    0,    0,    0,   59,   51,    0,    0,   59,
        0,    0,   53,   36,    0,    0,    0,    0,    0,    0,
        0,    0,   59,    0,    0,   60,   60,   60,   60,   59,
       50,   58,   49,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    5,    6,    1,    1,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   20,   20,   20,   20,   20,    1,   21,   22,
       23,   24,    1,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   44,   45,   46,   47,   48,   49,   41,
        1,    1,    1,    1,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   41,   67,   68,   69,   70,   71,   72,   73,
       74,   41,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[75] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    2,    2,    2,    2,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2
    } ;

static const flex_int16_t yy_base[280] =
    {   0,
        0,    0,    0,    0,  239, 1970, 1970, 1970,  199,   69,
       74, 1970, 1970, 1970, 1970, 1970,   60, 1970, 1970,   81,
     1970,   59, 1970,  195,   86,   91,  150,   87,  143,  161,
      160,  213,  117,  218,  227,  232,   88,  155,  256,  225,
      292,  282,  292,  297,  310, 1970, 1970,  198, 1970,  353,
      178, 1970,  336,  360,  365, 1970, 1970, 1970,    0,  370,
      375,  380,  388,  396,  404,  414,  430,  227,  435,  440,
      230,  448,  451,  452,  456,  489,  507,  554,  500,  561,
      533,  570,  518,  586,  595,  544,  610,  615,  608,  623,
      673,  678,  683,  695,  688,  688,  712,  738,  721,  743,

      748,  740,  758,  764,  770,  784,  796,  795,  790,  824,
      819,  845,  850,  855,  874,  879,  884,  901,  893,  894,
      901,  906,  918,  962,  968,  962,  986,  991, 1012, 1017,
     1025, 1030, 1023, 1047, 1053, 1073, 1079, 1085, 1090, 1102,
     1112, 1117, 1144, 1149, 1154, 1125, 1159, 1152, 1170, 1177,
     1182, 1206, 1211, 1216, 1224, 1231, 1241, 1246, 1265, 1270,
     1285, 1295, 1300, 1306, 1311, 1320, 1325, 1332, 1339, 1352,
     1358, 1364,  960, 1381, 1386, 1392, 1406, 1411, 1430, 1405,
     1435, 1428, 1430,  109,  118, 1455, 1480, 1489, 1455, 1499,
     1492, 1516, 1509, 1553, 1559, 1569, 1574, 1566, 1593, 1598,

     1616,   75,   80,   97, 1621, 1633, 1638, 1644, 1660, 1654,
     1672, 1678, 1704, 1718, 1713, 1725, 1717, 1735, 1741, 1746,
     1751, 1761,  138, 1769, 1774,  131, 1970,  138, 1779, 1784,
     1776, 1800, 1805, 1810,  651, 1068,  145,  286, 1260,  198,
     1820, 1826,  144,  106,  158, 1831, 1836, 1851, 1856, 1861,
      162,  127, 1970, 1866, 1882, 1887,  328,  200,  479, 1902,
      411,  218, 1909,  203,  210, 1970,  122,  107, 1970, 1894,
     1970, 1970, 1923, 1970, 1963, 1965, 1967,   94,   82
    } ;

static const flex_int16_t yy_def[280] =
    {   0,
      274,    1,  275,  275,  274,  274,  274,  274,  274,  276,
      277,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  278,  278,  278,   27,  278,   27,
      278,  278,  278,  278,  278,  278,   36,   36,  278,   36,
       36,  278,  278,  278,  278,  274,  274,  276,  274,  276,
      277,  274,  277,  274,  274,  274,  274,  274,  279,  278,
      278,  278,  278,  278,  278,  278,  278,   36,  278,  278,
       36,   36,   36,  278,   36,   36,  278,  278,   36,  278,
      278,  278,  278,  278,  278,  278,  278,  278,   36,   36,
      278,  278,  278,  278,  278,   36,  276,  277,  274,  278,

      278,   36,  278,  278,  278,  278,  278,   36,   36,  278,
      278,  278,  278,  278,  278,  278,  278,  278,   36,   36,
       36,   36,   36,  278,  278,   36,  278,  278,  278,  278,
      278,  278,   36,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  276,  277,  278,  278,  278,   36,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  274,  278,  278,  278,  278,  278,  278,   36,
      278,   36,   36,  276,  277,  278,  278,  278,   36,  278,
       36,  278,   36,  278,  278,  278,  278,   36,  278,  278,

      278,  274,  274,  274,  278,  278,  278,  278,  278,   36,
      278,  278,  276,  277,  278,  278,   36,  278,  278,  278,
      278,  278,  274,  278,  278,  274,  274,  274,  278,  278,
       36,  278,  278,  278,  276,  276,  276,  277,  277,  277,
      278,  278,  274,  274,  274,  278,  278,  276,  277,  278,
      274,  274,  274,  278,  276,  276,  276,  276,  277,  277,
      277,  277,  278,  274,  274,  274,  276,  277,  274,  278,
      274,  274,  278,    0,  274,  274,  274,  274,  274
    } ;

static const flex_int16_t yy_nxt[2045] =
    {   0,
        6,    7,    7,    8,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   20,   20,   20,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   35,
       35,   40,   41,   42,   43,   44,   45,   35,   35,   35,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   35,   40,   41,   42,   43,
       44,   45,   35,   35,   49,   54,   54,   54,   54,   54,
       52,   56,   57,   59,   50,   50,   50,   50,   50,   53,
       53,   53,   53,   53,   55,   60,   54,   54,   54,   54,

       54,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   69,   83,   52,   49,   70,   60,  227,   60,   63,
       84,  213,  226,   61,   52,   60,   60,   49,   71,  228,
      214,   62,   59,   59,   59,   59,   59,   69,   83,   64,
      223,   70,   60,  227,   60,   63,   84,  226,  252,   61,
       49,   60,   60,   71,   78,  228,   62,  248,   59,   59,
       59,   59,   59,  244,   64,   59,   59,   59,   59,   59,
      265,  243,  245,  252,   65,   59,   59,   59,   59,   59,
       78,   66,  251,   60,   52,   60,  253,   60,   67,  244,
       72,   68,   60,   85,  264,  265,   73,  243,  245,   74,

       65,   76,   75,   49,   52,  266,  267,   66,  251,   60,
      249,   60,  253,   60,   67,   72,   68,   58,   60,   85,
      264,   47,   73,  268,  269,   74,   76,   75,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,  274,  274,
      271,   77,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,  272,   60,  274,  107,   79,   60,   60,   60,
       80,  274,   60,   87,   81,   60,  271,   77,  111,  274,
       82,   59,   59,   59,   59,   59,  274,  272,  274,   60,
      274,  107,   79,   60,   60,   60,   80,  274,   60,   87,
       81,   60,   52,   86,  111,  274,   82,   59,   59,   59,

       59,   59,  240,  240,  240,  240,   93,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,  274,  274,   86,
       88,   95,  274,   89,   60,   59,   59,   59,   59,   59,
       60,   94,   93,  266,  267,   90,   91,  274,  274,  274,
       92,   96,   52,  258,  258,  274,   88,   95,  274,   89,
       60,   98,   98,   98,   98,   98,   60,   94,   49,  274,
       90,   91,  274,  274,  274,   92,  274,   96,   97,   97,
       97,   97,   97,   55,  274,   54,   54,   54,   54,   54,
       99,   99,   99,   99,   99,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,

      274,  274,  100,   59,   59,   59,   59,   59,  274,  274,
      101,   59,   59,   59,   59,   59,  268,  269,  102,   59,
       59,   59,   59,   59,  274,  274,  262,  262,  100,   59,
       59,   59,   59,   59,  274,  274,  101,  274,  104,  103,
      274,  274,  274,  274,  102,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
      274,  274,  274,  274,  104,  103,  105,   59,   59,   59,
       59,   59,  274,  274,  106,  109,   60,  274,  108,   60,
      112,  274,  110,   60,   60,   52,   60,  113,   60,  114,
      274,  274,  105,  115,  116,  262,  262,  262,  262,  106,

      274,  109,   60,  108,  274,   60,  112,  110,  274,   60,
       60,  274,   60,  113,   60,  114,  274,   60,  115,  274,
      116,   60,   59,   59,   59,   59,   59,  117,   60,  274,
      274,  274,  124,   59,   59,   59,   59,   59,   60,  274,
      274,  274,  118,   60,  274,  274,  274,   60,   59,   59,
       59,   59,   59,  117,   60,  274,  274,  274,  124,   59,
       59,   59,   59,   59,   60,  128,  274,  126,  118,   59,
       59,   59,   59,   59,  274,  274,   59,   59,   59,   59,
       59,  119,  274,  120,  274,   59,   59,   59,   59,   59,
      128,  121,  274,  126,  127,  274,  122,  123,  125,  274,

      274,   59,   59,   59,   59,   59,  274,  119,  274,  120,
       59,   59,   59,   59,   59,  274,  274,  121,  274,  274,
      127,  122,  123,  129,  125,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,  274,   60,  274,  130,  274,
       60,  274,  274,  274,  274,  131,  135,  274,  274,  129,
      133,   60,  274,  274,  132,   60,   49,  274,  134,  274,
      274,  136,   60,  130,  274,  274,   60,  237,  237,  237,
      237,  131,  135,  274,  274,  274,  133,   60,  274,  132,
      274,   60,  274,  134,  274,  274,  274,  136,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,

       59,   59,   59,   59,   59,   59,   59,   59,  139,  137,
       59,   59,   59,   59,   59,  138,  142,   49,  274,  274,
       60,  274,  140,  141,  274,  274,   60,  143,  143,  143,
      143,  143,  274,  274,  139,  137,   99,   99,   99,   99,
       99,  138,  142,  274,   52,  274,   60,  274,  140,  141,
      274,  274,   60,  144,  144,  144,  144,  144,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   60,  274,
      274,  274,  145,   59,   59,   59,   59,   59,   60,   59,
       59,   59,   59,   59,  146,   59,   59,   59,   59,   59,
      274,  274,  274,  274,   60,  274,  274,  274,  145,   59,

       59,   59,   59,   59,   60,  147,  148,  274,  274,  274,
      146,   59,   59,   59,   59,   59,  274,  274,  153,  151,
      150,  149,   60,  152,  274,  274,  274,   60,   60,  274,
      147,  274,  148,   60,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,  153,  151,  150,  149,   60,  152,
      154,  274,  274,   60,   60,  274,  274,  274,  155,   60,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,  274,  154,  274,  274,  159,
      274,  274,  274,  274,  155,  158,  274,  156,  157,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,

       59,   59,   59,   59,  274,  159,  274,  274,  274,  274,
      160,  158,  156,  157,  274,  161,   59,   59,   59,   59,
       59,  164,   60,  274,  274,   60,  165,  274,  162,  166,
      274,   60,   60,   60,  167,  274,  160,  274,   60,   60,
      163,  161,  274,  274,   60,  274,   60,  164,   60,  274,
       60,   60,  165,  162,  274,  166,  168,   60,   60,   60,
      167,  274,  173,  274,   60,   60,  163,  274,  274,  274,
       60,  274,   60,  274,  274,  274,   60,   59,   59,   59,
       59,   59,  168,   59,   59,   59,   59,   59,  202,  274,
      171,  274,  203,  274,   60,  204,  274,  274,  170,  169,

       60,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,  274,  274,  172,  202,  274,  171,  274,  203,  173,
       60,  204,  274,  274,  170,  169,   60,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,  274,  274,  172,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
      274,  176,  274,  274,  274,   60,  274,  274,  274,  274,
      174,   60,   59,   59,   59,   59,   59,  175,   59,   59,
       59,   59,   59,   49,  274,  274,  274,  176,  274,  274,
      248,   60,  274,  237,  237,  237,  174,   60,   59,   59,
       59,   59,   59,  175,   59,   59,   59,   59,   59,  177,

       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
      274,  179,  274,  274,  178,  274,  274,   59,   59,   59,
       59,   59,  274,  274,  177,  180,  181,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,  179,  274,  178,
       59,   59,   59,   59,   59,  274,  274,  274,  274,   49,
      274,  180,  181,  274,  274,   52,  182,  274,  183,  184,
      184,  184,  184,  184,  185,  185,  185,  185,  185,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,  274,
       60,  182,  274,  183,  187,   59,   59,   59,   59,   59,
       60,  186,   59,   59,   59,   59,   59,   59,   59,   59,

       59,   59,  274,  274,  274,  274,   60,  274,  274,  274,
      187,  274,  274,  188,  274,  274,   60,  186,  274,  274,
      189,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,  274,  274,  188,   59,
       59,   59,   59,   59,  274,  189,   59,   59,   59,   59,
       59,  274,  274,  274,  191,  190,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   52,  274,  274,  274,
      193,  274,  249,  274,  192,  240,  240,  240,  274,  191,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
      274,  274,  274,  274,  195,  274,  193,  274,  274,  192,

       59,   59,   59,   59,   59,  274,  274,  274,  194,  274,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
      195,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,  274,  274,  194,  196,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,  274,  198,   59,   59,   59,
       59,   59,  274,  197,   59,   59,   59,   59,   59,  274,
      196,  199,  274,  274,  274,  274,  200,   59,   59,   59,
       59,   59,  198,   59,   59,   59,   59,   59,  197,   59,
       59,   59,   59,   59,  274,  274,  199,  274,  274,  274,
      274,  200,  274,  274,  274,  201,   59,   59,   59,   59,

       59,   59,   59,   59,   59,   59,  205,   59,   59,   59,
       59,   59,  274,  206,  274,  274,  274,  274,  207,  274,
      201,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,  274,  205,  209,  274,  208,  274,   60,  274,  206,
      274,  274,  274,   60,  207,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,  274,  211,  274,  212,  209,
       60,  208,   60,   60,  274,  274,   60,  274,   60,   60,
       59,   59,   59,   59,   59,  274,  274,  274,  210,  274,
      274,  274,  211,  216,  212,  274,   60,   60,   60,  274,
      274,  274,   60,   60,   60,   59,   59,   59,   59,   59,

      274,  274,  274,  210,   59,   59,   59,   59,   59,  216,
      274,  274,  274,   60,   59,   59,   59,   59,   59,   60,
      218,  274,  274,  215,   60,  274,  274,  274,  217,  274,
       60,   59,   59,   59,   59,   59,  274,   60,  274,  274,
      274,  220,  274,  274,  274,  274,  218,   60,  215,  274,
       60,  274,  274,  274,  217,  274,   60,  274,  219,  274,
      274,  274,  274,   60,  274,  274,  274,  220,   59,   59,
       59,   59,   59,   60,   59,   59,   59,   59,   59,  274,
      274,  274,  274,  219,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,  222,  223,  274,  274,   60,  274,

      274,  274,  221,  274,   60,  274,  274,  274,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,  274,  274,
      222,  274,  274,  274,   60,  274,  274,  221,  274,  274,
       60,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,  224,  274,  274,  274,  229,  274,  225,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,  274,   59,
       59,   59,   59,   59,  274,  274,  224,  274,  274,  274,
      274,  229,  274,  225,  231,   59,   59,   59,   59,   59,
      274,  230,  233,  274,  274,  274,   60,   59,   59,   59,
       59,   59,   60,   59,   59,   59,   59,   59,  274,  274,

      231,  274,  232,  274,  274,  274,  230,  274,  233,   49,
      274,  274,   60,  274,  234,  274,  274,  274,   60,  235,
      236,  237,  237,  237,   52,  274,  274,  232,   59,   59,
       59,   59,   59,  238,  239,  240,  240,  240,  274,  234,
       59,   59,   59,   59,   59,   60,  274,  274,  274,   60,
       59,   59,   59,   59,   59,  241,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   60,  274,  274,  274,   60,   59,   59,   59,   59,
       59,  241,  274,  242,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,

       59,   59,   59,   59,  247,  246,  274,  274,   60,  242,
      274,  274,  274,  274,   60,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
      247,  246,  274,  274,   60,   59,   59,   59,   59,   59,
       60,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   49,  274,  274,  274,
      274,  250,   52,  274,  274,  254,  255,  256,  256,  257,
      258,  259,  260,  260,  261,  262,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,  250,   49,  274,  274,
      274,  254,  266,  267,  274,  274,  274,  263,  258,  258,

      258,  258,  258,  258,  258,  258,  258,  268,  269,   59,
       59,   59,   59,   59,  274,  274,  274,  262,  262,  262,
      262,  262,  274,  263,   59,   59,   59,   59,   59,  274,
      274,  274,  274,  270,  274,  274,  274,  273,   59,   59,
       59,   59,   59,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  270,
      274,  274,  273,   46,   46,   48,   48,   51,   51,    5,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274
    } ;

static const flex_int16_t yy_chk[2045] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   10,   17,   17,   17,   17,   17,
       11,   22,   22,  279,   10,   10,   10,   10,   10,   11,
       11,   11,   11,   11,   20,  278,   20,   20,   20,   20,

       20,   25,   25,   25,   25,   25,   26,   26,   26,   26,
       26,   28,   37,  268,  184,   28,   37,  203,   28,   26,
       37,  184,  202,   25,  185,   28,   37,  267,   28,  204,
      185,   25,   33,   33,   33,   33,   33,   28,   37,   26,
      223,   28,   37,  203,   28,   26,   37,  202,  244,   25,
      237,   28,   37,   28,   33,  204,   25,  237,   29,   29,
       29,   29,   29,  226,   26,   27,   27,   27,   27,   27,
      252,  223,  228,  244,   27,   31,   31,   31,   31,   31,
       33,   27,  243,   38,   51,   30,  245,   38,   27,  226,
       29,   27,   30,   38,  251,  252,   30,  223,  228,   30,

       27,   31,   30,   48,  240,  258,  258,   27,  243,   38,
      240,   30,  245,   38,   27,   29,   27,   24,   30,   38,
      251,    9,   30,  262,  262,   30,   31,   30,   32,   32,
       32,   32,   32,   34,   34,   34,   34,   34,    5,    0,
      264,   32,   35,   35,   35,   35,   35,   36,   36,   36,
       36,   36,  265,   40,    0,   68,   34,   40,   71,   68,
       36,    0,   71,   40,   36,   68,  264,   32,   71,    0,
       36,   39,   39,   39,   39,   39,    0,  265,    0,   40,
        0,   68,   34,   40,   71,   68,   36,    0,   71,   40,
       36,   68,  238,   39,   71,    0,   36,   42,   42,   42,

       42,   42,  238,  238,  238,  238,   42,   43,   43,   43,
       43,   43,   44,   44,   44,   44,   44,    0,    0,   39,
       41,   44,    0,   41,   41,   45,   45,   45,   45,   45,
       41,   43,   42,  257,  257,   41,   41,    0,    0,    0,
       41,   45,   53,  257,  257,    0,   41,   44,    0,   41,
       41,   53,   53,   53,   53,   53,   41,   43,   50,    0,
       41,   41,    0,    0,    0,   41,    0,   45,   50,   50,
       50,   50,   50,   54,    0,   54,   54,   54,   54,   54,
       55,   55,   55,   55,   55,   60,   60,   60,   60,   60,
       61,   61,   61,   61,   61,   62,   62,   62,   62,   62,

        0,    0,   61,   63,   63,   63,   63,   63,    0,    0,
       62,   64,   64,   64,   64,   64,  261,  261,   63,   65,
       65,   65,   65,   65,    0,    0,  261,  261,   61,   66,
       66,   66,   66,   66,    0,    0,   62,    0,   66,   65,
        0,    0,    0,    0,   63,   67,   67,   67,   67,   67,
       69,   69,   69,   69,   69,   70,   70,   70,   70,   70,
        0,    0,    0,    0,   66,   65,   67,   74,   74,   74,
       74,   74,    0,    0,   67,   70,   72,    0,   69,   73,
       72,    0,   70,   73,   75,  259,   72,   72,   75,   73,
        0,    0,   67,   74,   75,  259,  259,  259,  259,   67,

        0,   70,   72,   69,    0,   73,   72,   70,    0,   73,
       75,    0,   72,   72,   75,   73,    0,   76,   74,    0,
       75,   76,   77,   77,   77,   77,   77,   76,   79,    0,
        0,    0,   79,   83,   83,   83,   83,   83,   79,    0,
        0,    0,   77,   76,    0,    0,    0,   76,   81,   81,
       81,   81,   81,   76,   79,    0,    0,    0,   79,   86,
       86,   86,   86,   86,   79,   83,    0,   81,   77,   78,
       78,   78,   78,   78,    0,    0,   80,   80,   80,   80,
       80,   78,    0,   78,    0,   82,   82,   82,   82,   82,
       83,   78,    0,   81,   82,    0,   78,   78,   80,    0,

        0,   84,   84,   84,   84,   84,    0,   78,    0,   78,
       85,   85,   85,   85,   85,    0,    0,   78,    0,    0,
       82,   78,   78,   84,   80,   87,   87,   87,   87,   87,
       88,   88,   88,   88,   88,    0,   89,    0,   85,    0,
       89,    0,    0,    0,    0,   87,   89,    0,    0,   84,
       88,   90,    0,    0,   87,   90,  235,    0,   88,    0,
        0,   90,   89,   85,    0,    0,   89,  235,  235,  235,
      235,   87,   89,    0,    0,    0,   88,   90,    0,   87,
        0,   90,    0,   88,    0,    0,    0,   90,   91,   91,
       91,   91,   91,   92,   92,   92,   92,   92,   93,   93,

       93,   93,   93,   95,   95,   95,   95,   95,   93,   91,
       94,   94,   94,   94,   94,   92,   96,   97,    0,    0,
       96,    0,   94,   95,    0,    0,   96,   97,   97,   97,
       97,   97,    0,    0,   93,   91,   99,   99,   99,   99,
       99,   92,   96,    0,   98,    0,   96,    0,   94,   95,
        0,    0,   96,   98,   98,   98,   98,   98,  100,  100,
      100,  100,  100,  101,  101,  101,  101,  101,  102,    0,
        0,    0,  102,  103,  103,  103,  103,  103,  102,  104,
      104,  104,  104,  104,  103,  105,  105,  105,  105,  105,
        0,    0,    0,    0,  102,    0,    0,    0,  102,  106,

      106,  106,  106,  106,  102,  104,  105,    0,    0,    0,
      103,  107,  107,  107,  107,  107,    0,    0,  109,  108,
      107,  106,  109,  108,    0,    0,    0,  108,  109,    0,
      104,    0,  105,  108,  111,  111,  111,  111,  111,  110,
      110,  110,  110,  110,  109,  108,  107,  106,  109,  108,
      110,    0,    0,  108,  109,    0,    0,    0,  111,  108,
      112,  112,  112,  112,  112,  113,  113,  113,  113,  113,
      114,  114,  114,  114,  114,    0,  110,    0,    0,  114,
        0,    0,    0,    0,  111,  113,    0,  112,  112,  115,
      115,  115,  115,  115,  116,  116,  116,  116,  116,  117,

      117,  117,  117,  117,    0,  114,    0,    0,    0,    0,
      115,  113,  112,  112,    0,  116,  118,  118,  118,  118,
      118,  119,  120,    0,    0,  119,  120,    0,  117,  121,
        0,  119,  120,  121,  122,    0,  115,    0,  122,  121,
      118,  116,    0,    0,  122,    0,  123,  119,  120,    0,
      123,  119,  120,  117,    0,  121,  123,  119,  120,  121,
      122,    0,  173,    0,  122,  121,  118,    0,    0,    0,
      122,    0,  123,    0,    0,    0,  123,  124,  124,  124,
      124,  124,  123,  125,  125,  125,  125,  125,  173,    0,
      126,    0,  173,    0,  126,  173,    0,    0,  125,  124,

      126,  127,  127,  127,  127,  127,  128,  128,  128,  128,
      128,    0,    0,  127,  173,    0,  126,    0,  173,  130,
      126,  173,    0,    0,  125,  124,  126,  129,  129,  129,
      129,  129,  130,  130,  130,  130,  130,    0,    0,  127,
      131,  131,  131,  131,  131,  132,  132,  132,  132,  132,
        0,  133,    0,    0,    0,  133,    0,    0,    0,    0,
      131,  133,  134,  134,  134,  134,  134,  132,  135,  135,
      135,  135,  135,  236,    0,    0,    0,  133,    0,    0,
      236,  133,    0,  236,  236,  236,  131,  133,  136,  136,
      136,  136,  136,  132,  137,  137,  137,  137,  137,  135,

      138,  138,  138,  138,  138,  139,  139,  139,  139,  139,
        0,  138,    0,    0,  136,    0,    0,  140,  140,  140,
      140,  140,    0,    0,  135,  139,  140,  141,  141,  141,
      141,  141,  142,  142,  142,  142,  142,  138,    0,  136,
      146,  146,  146,  146,  146,    0,    0,    0,    0,  143,
        0,  139,  140,    0,    0,  144,  141,    0,  142,  143,
      143,  143,  143,  143,  144,  144,  144,  144,  144,  145,
      145,  145,  145,  145,  147,  147,  147,  147,  147,    0,
      148,  141,    0,  142,  148,  149,  149,  149,  149,  149,
      148,  145,  150,  150,  150,  150,  150,  151,  151,  151,

      151,  151,    0,    0,    0,    0,  148,    0,    0,    0,
      148,    0,    0,  149,    0,    0,  148,  145,    0,    0,
      150,  152,  152,  152,  152,  152,  153,  153,  153,  153,
      153,  154,  154,  154,  154,  154,    0,    0,  149,  155,
      155,  155,  155,  155,    0,  150,  156,  156,  156,  156,
      156,    0,    0,    0,  153,  152,  157,  157,  157,  157,
      157,  158,  158,  158,  158,  158,  239,    0,    0,    0,
      158,    0,  239,    0,  156,  239,  239,  239,    0,  153,
      159,  159,  159,  159,  159,  160,  160,  160,  160,  160,
        0,    0,    0,    0,  160,    0,  158,    0,    0,  156,

      161,  161,  161,  161,  161,    0,    0,    0,  159,    0,
      162,  162,  162,  162,  162,  163,  163,  163,  163,  163,
      160,  164,  164,  164,  164,  164,  165,  165,  165,  165,
      165,    0,    0,  159,  162,  166,  166,  166,  166,  166,
      167,  167,  167,  167,  167,    0,  165,  168,  168,  168,
      168,  168,    0,  164,  169,  169,  169,  169,  169,    0,
      162,  166,    0,    0,    0,    0,  167,  170,  170,  170,
      170,  170,  165,  171,  171,  171,  171,  171,  164,  172,
      172,  172,  172,  172,    0,    0,  166,    0,    0,    0,
        0,  167,    0,    0,    0,  170,  174,  174,  174,  174,

      174,  175,  175,  175,  175,  175,  174,  176,  176,  176,
      176,  176,    0,  175,    0,    0,    0,    0,  176,    0,
      170,  177,  177,  177,  177,  177,  178,  178,  178,  178,
      178,    0,  174,  180,    0,  178,    0,  180,    0,  175,
        0,    0,    0,  180,  176,  179,  179,  179,  179,  179,
      181,  181,  181,  181,  181,    0,  182,    0,  183,  180,
      182,  178,  183,  180,    0,    0,  182,    0,  183,  180,
      186,  186,  186,  186,  186,    0,    0,    0,  181,    0,
        0,    0,  182,  189,  183,    0,  182,  189,  183,    0,
        0,    0,  182,  189,  183,  187,  187,  187,  187,  187,

        0,    0,    0,  181,  188,  188,  188,  188,  188,  189,
        0,    0,    0,  189,  190,  190,  190,  190,  190,  189,
      191,    0,    0,  187,  191,    0,    0,    0,  190,    0,
      191,  192,  192,  192,  192,  192,    0,  193,    0,    0,
        0,  193,    0,    0,    0,    0,  191,  193,  187,    0,
      191,    0,    0,    0,  190,    0,  191,    0,  192,    0,
        0,    0,    0,  193,    0,    0,    0,  193,  194,  194,
      194,  194,  194,  193,  195,  195,  195,  195,  195,    0,
        0,    0,    0,  192,  196,  196,  196,  196,  196,  197,
      197,  197,  197,  197,  198,  199,    0,    0,  198,    0,

        0,    0,  195,    0,  198,    0,    0,    0,  199,  199,
      199,  199,  199,  200,  200,  200,  200,  200,    0,    0,
      198,    0,    0,    0,  198,    0,    0,  195,    0,    0,
      198,  201,  201,  201,  201,  201,  205,  205,  205,  205,
      205,  200,    0,    0,    0,  205,    0,  201,  206,  206,
      206,  206,  206,  207,  207,  207,  207,  207,    0,  208,
      208,  208,  208,  208,    0,    0,  200,    0,    0,    0,
        0,  205,    0,  201,  208,  209,  209,  209,  209,  209,
        0,  207,  210,    0,    0,    0,  210,  211,  211,  211,
      211,  211,  210,  212,  212,  212,  212,  212,    0,    0,

      208,    0,  209,    0,    0,    0,  207,    0,  210,  213,
        0,    0,  210,    0,  211,    0,    0,    0,  210,  213,
      213,  213,  213,  213,  214,    0,    0,  209,  215,  215,
      215,  215,  215,  214,  214,  214,  214,  214,    0,  211,
      216,  216,  216,  216,  216,  217,    0,    0,    0,  217,
      218,  218,  218,  218,  218,  217,  219,  219,  219,  219,
      219,  220,  220,  220,  220,  220,  221,  221,  221,  221,
      221,  217,    0,    0,    0,  217,  222,  222,  222,  222,
      222,  217,    0,  220,  224,  224,  224,  224,  224,  225,
      225,  225,  225,  225,  229,  229,  229,  229,  229,  230,

      230,  230,  230,  230,  231,  229,    0,    0,  231,  220,
        0,    0,    0,    0,  231,  232,  232,  232,  232,  232,
      233,  233,  233,  233,  233,  234,  234,  234,  234,  234,
      231,  229,    0,    0,  231,  241,  241,  241,  241,  241,
      231,  242,  242,  242,  242,  242,  246,  246,  246,  246,
      246,  247,  247,  247,  247,  247,  248,    0,    0,    0,
        0,  241,  249,    0,    0,  246,  248,  248,  248,  248,
      248,  249,  249,  249,  249,  249,  250,  250,  250,  250,
      250,  254,  254,  254,  254,  254,  241,  255,    0,    0,
        0,  246,  256,  256,    0,    0,    0,  250,  255,  255,

      255,  255,  256,  256,  256,  256,  256,  260,  260,  270,
      270,  270,  270,  270,    0,    0,    0,  260,  260,  260,
      260,  260,    0,  250,  263,  263,  263,  263,  263,    0,
        0,    0,    0,  263,    0,    0,    0,  270,  273,  273,
      273,  273,  273,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  263,
        0,    0,  270,  275,  275,  276,  276,  277,  277,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,

      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "lex_sql.l"

#line 28 "lex_sql.l"
#include<string.h>
#include<stdio.h>

/**
 * flex 代码包含三个部分，使用 %% 分隔
 * 第一个部分的代码是C代码，flex会原样复制到目标文件中
 * 第二个部分是规则部分，使用正则表达式定义一系列规则
 * 第三个部分还是C代码，flex 会复制此段代码
 */

#include "sql/parser/parse_defs.h"
#include "common/log/log.h"
#include "yacc_sql.hpp"

#ifndef register
#define register 
#endif // register

extern int atoi();
extern double atof();

#define RETURN_TOKEN(token) LOG_DEBUG("%s", #token);return token
#line 1034 "lex_sql.cpp"
/* 词法分析器的基础设置 */
/* Prevent the need for linking with -lfl */
#define YY_NO_INPUT 1
/* 与yacc的接口,生成与 Bison 的纯解析器(pure parser)兼容的代码 */
/* 不区分大小写 */
/* 支持位置跟踪 */

/* 规则匹配的优先级：*/
/* 1. 匹配的规则长的优先 */
/* 2. 写在最前面的优先 */
/* yylval 就可以认为是 yacc 中 %union 定义的结构体(union 结构) */
#line 1046 "lex_sql.cpp"

#define INITIAL 0
#define STR 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 78 "lex_sql.l"


#line 1332 "lex_sql.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 275 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1970 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 80 "lex_sql.l"
// ignore whitespace
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 81 "lex_sql.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "lex_sql.l"
yylval->number=atoi(yytext); RETURN_TOKEN(NUMBER);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 84 "lex_sql.l"
yylval->floats=(float)(atof(yytext)); RETURN_TOKEN(FLOAT);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 86 "lex_sql.l"
RETURN_TOKEN(SEMICOLON);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 87 "lex_sql.l"
RETURN_TOKEN(MAX);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 88 "lex_sql.l"
RETURN_TOKEN(MIN);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 89 "lex_sql.l"
RETURN_TOKEN(AVG);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 90 "lex_sql.l"
RETURN_TOKEN(SUM);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 91 "lex_sql.l"
RETURN_TOKEN(COUNT);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 92 "lex_sql.l"
RETURN_TOKEN(DOT);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 93 "lex_sql.l"
RETURN_TOKEN(EXIT);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 94 "lex_sql.l"
RETURN_TOKEN(HELP);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 95 "lex_sql.l"
RETURN_TOKEN(DESC);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 96 "lex_sql.l"
RETURN_TOKEN(CREATE);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 97 "lex_sql.l"
RETURN_TOKEN(DROP);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 98 "lex_sql.l"
RETURN_TOKEN(TABLE);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 99 "lex_sql.l"
RETURN_TOKEN(TABLES);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 100 "lex_sql.l"
RETURN_TOKEN(INDEX);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 101 "lex_sql.l"
RETURN_TOKEN(ON);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 102 "lex_sql.l"
RETURN_TOKEN(SHOW);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 103 "lex_sql.l"
RETURN_TOKEN(SYNC);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 104 "lex_sql.l"
RETURN_TOKEN(SELECT);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 105 "lex_sql.l"
RETURN_TOKEN(CALC);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 106 "lex_sql.l"
RETURN_TOKEN(FROM);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 107 "lex_sql.l"
RETURN_TOKEN(WHERE);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 108 "lex_sql.l"
RETURN_TOKEN(AND);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 109 "lex_sql.l"
RETURN_TOKEN(INSERT);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "lex_sql.l"
RETURN_TOKEN(INTO);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 111 "lex_sql.l"
RETURN_TOKEN(VALUES);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 112 "lex_sql.l"
RETURN_TOKEN(DELETE);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 113 "lex_sql.l"
RETURN_TOKEN(UPDATE);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 114 "lex_sql.l"
RETURN_TOKEN(SET);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 115 "lex_sql.l"
RETURN_TOKEN(TRX_BEGIN);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 116 "lex_sql.l"
RETURN_TOKEN(TRX_COMMIT);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 117 "lex_sql.l"
RETURN_TOKEN(TRX_ROLLBACK);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 118 "lex_sql.l"
RETURN_TOKEN(INT_T);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 119 "lex_sql.l"
RETURN_TOKEN(STRING_T);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 120 "lex_sql.l"
RETURN_TOKEN(FLOAT_T);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 121 "lex_sql.l"
RETURN_TOKEN(DATE_T);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 122 "lex_sql.l"
RETURN_TOKEN(LOAD);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 123 "lex_sql.l"
RETURN_TOKEN(DATA);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 124 "lex_sql.l"
RETURN_TOKEN(INFILE);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 125 "lex_sql.l"
RETURN_TOKEN(EXPLAIN);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 126 "lex_sql.l"
RETURN_TOKEN(GROUP);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 127 "lex_sql.l"
RETURN_TOKEN(BY);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 128 "lex_sql.l"
RETURN_TOKEN(LENGTH);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 129 "lex_sql.l"
RETURN_TOKEN(ROUND);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 130 "lex_sql.l"
RETURN_TOKEN(DATE_FORMAT);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 131 "lex_sql.l"
RETURN_TOKEN(INNER_JOIN);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 132 "lex_sql.l"
RETURN_TOKEN(STORAGE);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 133 "lex_sql.l"
RETURN_TOKEN(FORMAT);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 134 "lex_sql.l"
RETURN_TOKEN(NOT_LIKE);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 135 "lex_sql.l"
RETURN_TOKEN(LIKE);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 136 "lex_sql.l"
RETURN_TOKEN(NOT_IN);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 137 "lex_sql.l"
RETURN_TOKEN(IN);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 138 "lex_sql.l"
RETURN_TOKEN(EXISTS);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 139 "lex_sql.l"
RETURN_TOKEN(NOT_EXISTS);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 141 "lex_sql.l"
yylval->string=strdup(yytext); RETURN_TOKEN(ID);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 142 "lex_sql.l"
yylval->string=strdup(yytext); RETURN_TOKEN(DATE_STR); 
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 144 "lex_sql.l"
RETURN_TOKEN(LBRACE);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 145 "lex_sql.l"
RETURN_TOKEN(RBRACE);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 147 "lex_sql.l"
RETURN_TOKEN(COMMA);
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 148 "lex_sql.l"
RETURN_TOKEN(EQ);
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 149 "lex_sql.l"
RETURN_TOKEN(LE);
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 150 "lex_sql.l"
RETURN_TOKEN(NE);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 151 "lex_sql.l"
RETURN_TOKEN(NE);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 152 "lex_sql.l"
RETURN_TOKEN(LT);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 153 "lex_sql.l"
RETURN_TOKEN(GE);
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 154 "lex_sql.l"
RETURN_TOKEN(GT);
	YY_BREAK
case 71:
#line 157 "lex_sql.l"
case 72:
#line 158 "lex_sql.l"
case 73:
#line 159 "lex_sql.l"
case 74:
YY_RULE_SETUP
#line 159 "lex_sql.l"
{ return yytext[0]; }
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 160 "lex_sql.l"
yylval->string = strdup(yytext); RETURN_TOKEN(SSS);
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 161 "lex_sql.l"
yylval->string = strdup(yytext); RETURN_TOKEN(SSS);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 163 "lex_sql.l"
LOG_DEBUG("Unknown character [%c]",yytext[0]); return yytext[0];
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 164 "lex_sql.l"
ECHO;
	YY_BREAK
#line 1773 "lex_sql.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 275 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 275 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 274);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 164 "lex_sql.l"


void scan_string(const char *str, yyscan_t scanner) {
  yy_switch_to_buffer(yy_scan_string(str, scanner), scanner);
}

